### ISSUE TITLE
duplicate case value error in getPropertyIndex(String name) method in a class that implements org.drools.model.DomainClassMetadata

### ISSUE THREAD

**Issue by rakeshnpatel** [kiegroup/kogito-runtimes#1181]
We have a domain model with 2 properties. 1 in the base class and the other in the parent class:

``` 
public Resource getResource() {

}
```

and
```
public boolean isResource() {

}
```

when Kogito generates the Metadata class that implements ``org.drools.model.DomainClassMetadata``, in the overridden method ``getPropertyIndex(String name)`` it generates duplicate case statement for ``resource`` property resulting in duplicate case statement compilation error.

Any workaround or fix for this ?

**Comment by tkobayas** [comment]
Thank you for reporting! I have filed a JIRA for the issue. 
https://issues.redhat.com/browse/DROOLS-6442

I'm afraid that there is no good workaround other than changing the property name.

I'm closing this github issue now (as we are mainly watching JIRA, Zulip and Kogito mailing list). Please kindly follow up / comment on the JIRA if necessary.

Thanks again.
