### ISSUE TITLE
ReflectionProtoGenerator - clazz.getDeclaredFields is not compatible with PropertyDescriptor

### ISSUE THREAD

**Issue by rakeshnpatel** [kiegroup/kogito-runtimes#1193]
```messageFromClass``` method iterates through all the properties of a given class. the properties are retrieved using Introspector which returns all the properties including that of super class(es).

however, inside the method we are checking for property accessors using java ```getDeclaredField()``` method call which only looks at current class.

this results into exception ```java.lang.NoSuchFieldException``` which is misleading.

Any workaround or fix for this would be appreciated.

**Comment by danielezonca** [comment]
Fixed by https://github.com/kiegroup/kogito-runtimes/pull/1586
