### ISSUE TITLE
Upgrade to Quarkus 2.0.0.CR3

### ISSUE THREAD

**Issue by ppalaga** [kiegroup/kogito-runtimes#1350]
Quarkus 2.0.0.CR3 was released today. Could you please upgrade in Kogito? 
We (Camel Quarkus) would very much appreciate a Kogito release based on Quarkus 2.0.0.CR3 to be able to test with Camel Quarkus and even on Quarkus Platform. Is there any hope for it?

**Comment by ricardozanini** [comment]
Hey @ppalaga! We've just upgraded: https://github.com/kiegroup/kogito-runtimes/blob/master/kogito-build/kogito-build-parent/pom.xml#L127

The artifacts for 1.8.0 release are already on Maven Central. Reach out to me if you have any problems.

**Comment by ppalaga** [comment]
Sorry for the spam, we actually do not depend on Kogito. I confused it with OptaPlanner.
