### ISSUE TITLE
kogito-addons-persistence-jdbc is not compatible with mariadb

### ISSUE THREAD

**Issue by air237** [kiegroup/kogito-runtimes#1615]
There are two sql files in the resources:
kogito-runtimes/addons/common/persistence/jdbc/src/main/resources/sql/
- create_tables.sql
- exists_tables.sql

These sql files are written in postgresql syntax. 
There is a specific addon for postgresql. The sql files in kogito-addons-persistence-jdbc should be written in standard sql.

**Comment by cristianonicolai** [comment]
@air237 a fix should be available on Kogito version 1.12, feel free to reopen in case still having issues with this.
