### ISSUE TITLE
Can not package on Windows10

### ISSUE THREAD

**Issue by wxyzyu** [kiegroup/kogito-runtimes#1825]
Hi, 
I'm trying Kogito wtih serverless workflow by running the kogito-examples.But I can not package the example project on Windows, while there seems to be no problem when I package on CentOS.

On Windows, the generated openapi sources are located in ".\kogito-examples-main\serverless-workflow-temperature-conversion\conversion-workflow\target\generated-sources\kogito\\**src\main\java**\org\kie\kogito\app\openapi\client" 

Is this because the following codes do not fit windows, or Kogito only supports linux system?
https://github.com/kiegroup/kogito-runtimes/blob/49c622f08f3803d27d0585adfdeabe93200f642e/kogito-codegen-modules/kogito-codegen-openapi/src/main/java/org/kie/kogito/codegen/openapi/client/GeneratedFileBuilder.java#L68

The following file tree is what Kogito generated after “mvn package”，and I ran into an error “The declared package "org.kie.kogito.app.openapi.client.c3BlY3MvbXVsdGlwbGljYXRpb24ueWFtbA___multiplication" does not match the expected package "src.main.java.org.kie.kogito.app.openapi.client.c3BlY3MvbXVsdGlwbGljYXRpb24ueWFtbA___multiplication“

└─kogito
---├─org
---│---└─kie
---│------└─kogito
---│---------├─app
---│---------├─handlers
---│---------└─serverless
---└─src
------└─main
---------└─java
------------└─org
---------------└─kie
------------------└─kogito
---------------------└─app
------------------------└─openapi
---------------------------└─client
------------------------------├─c3BlY3MvbXVsdGlwbGljYXRpb24ueWFtbA___multiplication
------------------------------│  └─auth
------------------------------└─c3BlY3Mvc3VidHJhY3Rpb24ueWFtbA___subtraction
---------------------------------└─auth

**Comment by ricardozanini** [comment]
Hi! Thanks for reporting it and sorry for the late reply. I've opened [KOGITO-6491](https://issues.redhat.com/browse/KOGITO-6491) to fix it. I will work on it ASAP.

Sorry for the late reply!

**Comment by ricardozanini** [comment]
@wxyzyu can you try the patch on #1832? You can easily and quickly build `kogito-runtimes` locally with `mvn clean install -Dquickly`.

**Comment by wxyzyu** [comment]
> @wxyzyu can you try the patch on #1832? You can easily and quickly build `kogito-runtimes` locally with `mvn clean install -Dquickly`.

Hi,
Thank you for your work. I have tried,and it works.The generated openapi client is in the right folder.
But some new problem occured:

1. when I started kogito-examples\serverless-workflow-temperature-conversion\conversion-workflow with "mvn clean package quarkus:dev", an error Caused by:" java.nio.file.InvalidPathException: Illegal char <:> at index 2: /E:/projects/kogito-examples/serverless-workflow-temperature-conversion/conversion-workflow/target/classes/specs/multiplication.yaml", so I modified the source code in org.kie.kogito.codegen.openapi.client.io.ClasspathResolver to remove the first "/" in file path.

2. after that, a new error :" Impossible to clean up OpenApi generator output dir

java.nio.file.NoSuchFileException: E:\projects\kogito-examples\serverless-workflow-temperature-conversion\conversion-workflow\target\openapi\c3BlY3MvbXVsdGlwbGljYXRpb24ueWFtbA==_multiplication"

**Comment by ricardozanini** [comment]
Interesting, I'll take a look at it

**Comment by ricardozanini** [comment]
Opened https://issues.redhat.com/browse/KOGITO-6522 to track it.

**Comment by wmedvede** [comment]
This issue was fixed as part of https://issues.redhat.com/browse/KOGITO-6522, the SW example should now work fine in windows too.
