### ISSUE TITLE
Swagger/OpenAPI generation docs? Explain what gets generated

### ISSUE THREAD

**Issue by StephenOTT** [kiegroup/kogito-runtimes#1871]
### Description

When you open a generated swagger UI there is lots of endpoints for a simple process (such as user tasks-quarkus), but Is there docs about what endpoints are generated and how/based on what data points?

**Comment by ricardozanini** [comment]
@StephenOTT the closer I could find in the docs is this section: https://docs.jboss.org/kogito/release/latest/html_single/#ref-bpmn-model-example_kogito-developing-process-services. I've opened [KOGITO-6559](https://issues.redhat.com/browse/KOGITO-6559) to follow-up this request. Thanks!
