### ISSUE TITLE
Quarkus Dev UI breaks during hot reload of BPMN change

### ISSUE THREAD

**Issue by StephenOTT** [kiegroup/kogito-runtimes#1873]
### Describe the bug

edit: this seems to break even after a full clean and compile.  

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/1994838/149633843-d4107a34-a70b-4f8d-9d65-ab9139a733ac.png">

Running https://github.com/kiegroup/kogito-examples/tree/stable/process-usertasks-quarkus

The change i made to the BPMN was to tag  firstLineApprover and secondLineApprover process variables as "internal" so they would not show in the swagger UI.

using quarkus:dev

Modified the BPMN in VS Code and when you refresh localhost:8080/q everything breaks:

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/1994838/149633133-5c44f880-de7e-4bcd-97d3-9ea7c87cf2c8.png">

and 

<img width="1325" alt="image" src="https://user-images.githubusercontent.com/1994838/149633143-b75bca7b-52f4-46c0-a9ab-c00b09c6d140.png">

**console does not show any errors.  It shows a successful live reload**

Thanks

**Comment by StephenOTT** [comment]
created: https://issues.redhat.com/browse/KOGITO-6570 as this is a very annoying bug to deal with given that hot reload is supposed to work.

**Comment by cristianonicolai** [comment]
@StephenOTT thanks for reporting. This seems to be fixed on version 1.16 which is about to be released. Thanks

**Comment by StephenOTT** [comment]
Thanks! Looking forward to it!

**Comment by StephenOTT** [comment]
@cristianonicolai yes this appears to be fixed in 1.16.  Thanks
