### ISSUE TITLE
Comments/Attachments on User Tasks should generate process events with the comment/attachment data - Missing Context for triggering Event?

### ISSUE THREAD

**Issue by StephenOTT** [kiegroup/kogito-runtimes#1874]
### Description

When a EventPublisher consumes `DataEvent`s and the /comments and /attachment endpoints are used, there should be a event generated that contains the Comment/Attachment.

An Event is generated (ProcessInstanceDataEvent and a UserTaskInstanceDataEvent), but the event does not seem to contain the comment/attachment data.

**Comment by StephenOTT** [comment]
UPDATE:

After further investigation, I am now seeing the comments as part of the Data property: so to recap based on this finding:

Process Events are essentially snapshots of the data (Process, UserTasks and Variables)?

Is there context about what triggered the event? (something that alludes to the UserTaskInstanceDataEvent was generated because a comment was added/removed, etc?)


What are the conditions for a VariableInstanceDataEvent to be generated?  Example, I see that if you update a user task's variables with a PUT it generates a UserTaskInstanceDataEvent instead of a variable event.  And if i do a PUT on the process and update the variables it generates a ProcessInstanceDataEvent instead of a variable event?  (both again without context to the action that occurred to generate the event?)

Thanks!

**Comment by fjtirado** [comment]
A VariableInstanceEvent is generated when you do a PUT on the process and update the variables. 
Since, as you already mentioned, these events are snapshots and not incremental ones, there is no context of what really changed from one snapshot to another

**Comment by fjtirado** [comment]
UserTaskDeadline handling for Kogito is explained in this blog entry https://blog.kie.org/2021/08/kogito-task-deadlines.html

**Comment by StephenOTT** [comment]
@fjtirado my concern/thought comes from audit trail generation.  The events give you the data, BUT it seems the context of the event is lost?  Such as yes a snapshot was generated, but WHY was it generated?  "what command in the system triggered the event generation?"

**Comment by StephenOTT** [comment]
@fjtirado using the process-usertask-quarkus example, I can run a PUT on the /approvals endpoint for a instance that was previously created, and doing a change the the variables:

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/1994838/149815660-f12c7b6b-c14b-4918-9109-eabd9ad82204.png">


it generates a ProcessInstanceDataEvent, not a VariableInstance event.

Is this a bug?

**Comment by fjtirado** [comment]
Take into account that this event clasess were designed with data index on mind (data index population is based on snapshots)
For operation recording (or audit) these events are indeed not so useful, but still you can find out what change (and the change is the why) comparing two consecutive snapshots (assuming you are storing them)
PS I perfectly understand your concern, eventually we will need either to add context to snapshots or create a different topic for audit.

**Comment by fjtirado** [comment]
I will take a look at the presumed bug and confirm

**Comment by fjtirado** [comment]
https://issues.redhat.com/browse/KOGITO-6568 was opened for the audit thing
