### ISSUE TITLE
Enable/Disable option for Comments and Attachments in a process

### ISSUE THREAD

**Issue by StephenOTT** [kiegroup/kogito-runtimes#1875]
### Description

In many cases you don't always want the comments and attachment endpoints being generated.  Would be great to have the ability to disable these features.

**Comment by fjtirado** [comment]
The fact that an endpoint is there, does not necessarily means you need to use it. But comments/attachments are part of the task (as any other field there) and cannot be disable on demand. Since having two extra endpoint  has not any impact on performance, I cannot see this as a valid issue.

**Comment by StephenOTT** [comment]
@fjtirado thanks for the quick feedback.  How are you choosing endpoints that go into the default vs management endpoints?

**Comment by fjtirado** [comment]
@StephenOTT Thats a pretty good quesiton. If I recall my own rationale correctly, after much thought (Becasue it is a corner case, so whatever decision we have taken will be valid or invalid no matter which one we have taken ;)), I put attachment/comments on runtime API  becase I consider them operations more closely related to task life cycle than task  user or metadata management (for example, a user might want to add a file/comment before or after changing to complete, while chaning description or changing the assigned user is more related with task "metadata", an operation completely independent on the task life cycle).

**Comment by fjtirado** [comment]
On the other hand, comments and attachments are always the same regardless of the task, so they can be perfectly be on management. As I said, it is just a matter of taste.

**Comment by StephenOTT** [comment]
Okay, and if the ~design around access to these endpoints based on a API gateway that controls permissions to the endpoint or essentially using something like: https://quarkus.io/guides/security-authorization#authorization-using-configuration ?  

Comments/attachments could be seen as typical user functions, but then we get into the ability to change phases, modify existing comments, etc.  I ask this as removal of the endpoints would be one way to "Secure" those functions.  But if they will be created, then what is the security process for the endpoint and the individual functionality?  (Such as modifying comments of others? modifying your own comments? commenting on tasks you are not assigned to?, etc).

**Comment by StephenOTT** [comment]
In a similar vein, are there handlers/listeners for comments and attachments that can overwritten?  So attachments can be stored in a custom location / processed in a custom way?

**Comment by fjtirado** [comment]
An attachment is just a link to an already stored resource somewhere else. The responsible for storing the resource is the caller of the API. This is a conscious decision to avoid using Kogito runtimes db as a data store for attachment content.

**Comment by fjtirado** [comment]
To be honest, I think that even in that use case the endpoint still make sense. You still want to link the URI you are creating with the task and for that you will use the existing endpoint. What I will do is to create an additional endpoint that accepts the byte[] content, that store that byte[] in the DB of you choice and then call the existing point.

**Comment by StephenOTT** [comment]
Agreed that is an option.  Why would you call the second REST API vs adding an attachment through the java api?

**Comment by fjtirado** [comment]
For security please ignore that documentation section, it is a leftover. 
1) This runtimes API is supposed to be called from a gateway API which security constraints Im not really familiar with
2) In case it is directly invoked, you probably have noticed that every generated endpoint has two extra parameters: user and group. 
After going through some layers, this user and group are used here
https://github.com/kiegroup/kogito-runtimes/blob/main/jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/humantask/HumanTaskWorkItemImpl.java#L145-L201

**Comment by fjtirado** [comment]
> 



> Agreed that is an option. Why would you call the second REST API vs adding an attachment through the java api?

I was assuming the new endpoint is in a different server than the existing one. If you are using the same kogito instance, then you can just disable rest generation and generate your desired endpoints

**Comment by StephenOTT** [comment]
:) haha BUT I WANT THE BEST OF BOTH WORLDS :)  Generation + customization.  But understood 👍 thank you for all the details.  

In my use cases I am assuming that the Kogito app/server is what is "available" to the client/UI, and there is no additional server.  If kogito was designed for a different arch in mind, please let me know and i can adjust for this! :)

**Comment by fjtirado** [comment]
In theory you can take the generated endpoints and scaffold them (meaning you generate once and then you change them in your own) @evacchi can probably provide more insights into that
