### ISSUE TITLE
Filesystem persistence: Expected usage? (docs unclear)

### ISSUE THREAD

**Issue by StephenOTT** [kiegroup/kogito-runtimes#1877]
### Description

The docs reference filesystem persistence: https://docs.kogito.kie.org/latest/html_single/#_kogito_persistence_add_on

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/1994838/149670994-e808785b-8565-4dfc-b6c3-2fb631adf0f7.png">

but the persistence section of the docs does not speak to its usage, limitations, etc: https://docs.kogito.kie.org/latest/html_single/#con-persistence_kogito-developing-process-services

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/1994838/149670989-ae92f785-67f8-4d48-91f6-51af9a4f3465.png">

Happy to do doc updates if someone could explain the intended usage and limitations.

**Comment by fjtirado** [comment]
@hmanwani-rh I think this something we need to fix in the docs
@StephenOTT The main usage case for persistence, as you can guess, is for guys that want some form of primitive persistence and are not willing to install/use an external DB application.

**Comment by hmanwani-rh** [comment]
> @hmanwani-rh I think this something we need to fix in the docs @StephenOTT The main usage case for persistence, as you can guess, is for guys that want some form of primitive persistence and are not willing to install/use an external DB application.

@fjtirado @StephenOTT Thanks for letting me know. 
I've created https://issues.redhat.com/browse/BXMSDOC-8372 to improve the persistence content in Kogito docs.
