### ISSUE TITLE
OpenAPi codegen for processes should use Process Documentation and Start Event documentation to populate descriptions in openapi and swagger ui

### ISSUE THREAD

**Issue by StephenOTT** [kiegroup/kogito-runtimes#1886]
### Description

for a process there is the element doc and the "Process instances description" fields:

<img width="506" alt="image" src="https://user-images.githubusercontent.com/1994838/149807982-852873f6-cc35-411e-988a-5261853b37d2.png">

and on a start event we have: 
<img width="1958" alt="image" src="https://user-images.githubusercontent.com/1994838/149808044-ef59bf42-adfb-4e95-a578-87b258660d15.png">

This documentation would be very helpful add into the openapi spec / swagger ui. 

if multiple Start Events are supported, then having descriptions on what each event does in the swagger would be very valuable.

**Comment by ricardozanini** [comment]
Hi @StephenOTT! This is reasonable, opened https://issues.redhat.com/browse/KOGITO-6573 to track it.
