### ISSUE TITLE
Business Key is missing from default api responses of POST and GET process 

### ISSUE THREAD

**Issue by StephenOTT** [kiegroup/kogito-runtimes#1887]
### Describe the bug

When you create a process instance (such as in swagger ui), the business key is required.  But the Key is not returned in the response (but the process' ID is)

When you do a GET on the process ID, the business key is still not returned.

### Expected behavior

the business key being a required field would return in the instance generation response and on GET of the process instance.

**Comment by fjtirado** [comment]
This is being worked out here https://github.com/kiegroup/kogito-runtimes/pull/1868

**Comment by fjtirado** [comment]
Also, business key should be optional. But if is there, should be returned, now it is not

**Comment by StephenOTT** [comment]
Okay then ya it is currently mandatory in the current release.

**Comment by fjtirado** [comment]
@StephenOTT  with  #1868, business key will be made optional in swagger.
Can you create JIRA for including it in the response of GET and instance generation? I agree this is needed but it is a different JIRA and it is better to not mix things

**Comment by StephenOTT** [comment]
Created https://issues.redhat.com/browse/KOGITO-6569 for business key in responses
