### ISSUE TITLE
Docs on Public APIs for main Services to inject?

### ISSUE THREAD

**Issue by StephenOTT** [kiegroup/kogito-runtimes#1888]
### Description

Going through docs, code samples, and some of the management API, i have found the following services that seem to be referenced:
```
    AppRoot appRoot;
    Processes processes;
    Application application;
    ProcessService processService;
    PredictionService predictionService;
    StraightThroughProcessService straightThroughProcessService;
    RuleUnitService ruleUnitService;
    DecisionService svc;
```
But cannot find much in way of docs if these are the "main" services / top level APIs to access?

Typical entry points users want are:

1. Start process instances
2. Find existing instances, tasks, activities
3. Navigate a BPMN structure to query for some configuration in the BPMN
4. Get Data from the index service
5. Validate a user making the request against the config of the BPMN (does this user have X role, are they one of the users in the actor config of the BPMN user task, etc).

Is there some light list/doc can be provided on this?  What is the difference between, AppRoot, Processes, Application, and ProcessService for example.

**Comment by fjtirado** [comment]
@evacchi It is currently working on a new API, there is a brilliant sequence of post, I'm linking the last one https://blog.kie.org/2021/12/the-road-towards-a-public-api-part-2.html
And now, your question, 
Application (to be replaced by AppRoot, thats why I think you should go through Edoardo's work)  is the main entry point, from there you can navigate through processes. Processes are the reference to the generated process defintions (bpmn or serverless wokflow), from where you can create your process instances. 
ProcessService is an internal one, which you should ignore unless you are generating your own rest interface (it basically contains the operations that are triggered from REST generated classes.

**Comment by cristianonicolai** [comment]
@hmanwani-rh we should track this to be incorporated in the Kogito docs, do you mind creating a JIRA please.

**Comment by hmanwani-rh** [comment]
> @hmanwani-rh we should track this to be incorporated in the Kogito docs, do you mind creating a JIRA please.

@cristianonicolai I've created https://issues.redhat.com/browse/BXMSDOC-8371 to address these changes in Kogito docs.
