### ISSUE TITLE
/nodes management endpoint should provide node configurations

### ISSUE THREAD

**Issue by StephenOTT** [kiegroup/kogito-runtimes#1890]
### Description

consider:

<img width="1521" alt="image" src="https://user-images.githubusercontent.com/1994838/149835217-67f2e8bf-d40e-4de3-bfb5-fea6c9c28ef7.png">

from the process-usertask-quarkus example project.

One of the most common requests for introspection of BPMN is to get XYZ configuration properties for all values in a BPMN.  supporting this further enhances the ability of the SVG add-on to apply values on a SVG without having to introspect a BPMN JSON tree.

Currently the nodes being returned a basic.  But all of the configuration that was applied could be returned:

Examples:

1. Async Nodes
2. Documentation
3. Conditional Logic
4. Assignment logic
5. Tasks that have notification logic
6. Priority
7. Multi-instance configs
8. etc

### Implementation ideas

Enhance the Nodes endpoint to provide all of the configurations for each node.

**Comment by StephenOTT** [comment]
Could then do stuff like: https://github.com/StephenOTT/Cammand#bpmn-data-overlays

**Comment by cristianonicolai** [comment]
@StephenOTT let me just recap to make sure I got the idea right, so what you're suggesting is to extend the /nodes endpoint to include more information from the BPMN model. More specifically attributes from nodes like description, priority, possibly metadata and more so it would allow introspecting the model externally without actually getting to parse the BPMN model. Does that sounds about right?

**Comment by StephenOTT** [comment]
Yes.  Given that it seems pretty much everything is pushed into the "metadata" object? (with maybe some exceptions?), I would like to see "everything" added into this.  If its a BPMN config/attribute/detail, etc that gets loaded into the app, then it should be in the /node endpoint.

**Comment by StephenOTT** [comment]
Simple common Example: 

People want to generate process documentation: where they generate a PDF will all Nodes, their ID, titles, main configs, and the documentation field so they can have a audit trail / doc of what the BPMN does (from business perspective) and docs the setup at the time.

Imagine auditors come in later on and ask "how does this workflow work?" and they are not technical.  They want some sort of "doc".  The modellers do not want to manage this manually, they want the source bpmn config to be available and queryable.  If it was part of the endpoint then all of this data is easily accessible in JSON and life is MUCH easier!
