### ISSUE TITLE
Provide configuration option to add App description and details into the OpenAPI spec so it shows in the swagger UI

### ISSUE THREAD

**Issue by StephenOTT** [kiegroup/kogito-runtimes#1897]
### Description

<img width="1557" alt="image" src="https://user-images.githubusercontent.com/1994838/149953012-4167bf33-a898-4179-ae1e-f4761eea7642.png">

vs

<img width="1598" alt="image" src="https://user-images.githubusercontent.com/1994838/149953056-7be3217b-15f7-45e9-9992-9fee813fce01.png">

The swagger UI is often used in orgs as the first level of testing and quick use of a API.  ability to add additional contextual info about what this workflow app does, why, links, etc, would be VERY helpful for orgs and adoption.

**Comment by ricardozanini** [comment]
Created https://issues.redhat.com/browse/KOGITO-6577 to track it. Also relates with #1886
