### ISSUE TITLE
Understanding CodeGen generated classes against BPMN Model - Node Numbers vs TaskName value

### ISSUE THREAD

**Issue by StephenOTT** [kiegroup/kogito-runtimes#1904]
### Description

Consider the following:

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/1994838/150212028-5c34d1c0-662f-4b55-9beb-802b17de210f.png">

<img width="914" alt="image" src="https://user-images.githubusercontent.com/1994838/150212096-b83465cf-54cd-49b2-bfe3-5c7f85693fbd.png">

<img width="880" alt="image" src="https://user-images.githubusercontent.com/1994838/150212475-665b5114-4114-4e39-a548-3dddf174b1e4.png">

### Implementation ideas

Related to to issues in: https://github.com/kiegroup/kogito-runtimes/issues/1900

The naming of the files is generated based on Node numbers (which comes form where? Can i control this?)

Given that TaskName will be unique could generated classes have the TaskName instead of node number?

**Comment by fjtirado** [comment]
Yes, once the task name is unique, the node number is not longed needed
