### ISSUE TITLE
User Task Endpoint CodeGen: Claim, Unclaim, Assign, Delegate, etc?

### ISSUE THREAD

**Issue by StephenOTT** [kiegroup/kogito-runtimes#1908]
### Description

Docs reference ability to claim and other typical user task actions in BPM

typical:

1. Claim Task (the current user can claim the task / make themselves the Assignee)
2. Unclaim Task (The current user who is assigned to the task can unclaim themselves from the task)
3. Assign Task (userA assigning a task to userB, ex Manager assigns task to userA, or to assign to no one/remove any current claim/assignment)
4. Complete Task (submit data into the task and complete it)
5. Delegate (very much less used, so ignore for now)

How are the HTTP endpoints supposed to be used by a client to achieve actions actions 1-3?  number 4 would seem to be completed as part of the POST for the task instance.

**Comment by fjtirado** [comment]
Plese take a look to this post https://blog.kie.org/2021/05/kogito-user-tasks-process-api.html. All the operations you are describing should be implemented as lifecycle phases

**Comment by StephenOTT** [comment]
for ref: https://docs.jboss.org/kogito/release/latest/html_single/#con-task-lifecycle_kogito-developing-process-services
