### ISSUE TITLE
codeGen for java gateway logic is generating java variable code for every variable regardless of use

### ISSUE THREAD

**Issue by StephenOTT** [kiegroup/kogito-runtimes#1912]
### Describe the bug

When codegen generates a gateway logic for java code, it is creating code like this:

```java
       splitNode3.constraint(7, "_28939158-F15A-493C-A92E-7FA3FC34056B", "DROOLS_DEFAULT", "java", kcontext -> {
            java.lang.String approver = (java.lang.String) kcontext.getVariable("approver");
            org.acme.travels.Traveller traveller = (org.acme.travels.Traveller) kcontext.getVariable("traveller");
            java.lang.Boolean firstLineApproval = (java.lang.Boolean) kcontext.getVariable("firstLineApproval");
            java.lang.Boolean secondLineApproval = (java.lang.Boolean) kcontext.getVariable("secondLineApproval");
            return true;
        }, 0);
```

This does not appear correct / excessive code gen.  Imagine if you have 100 variables.  Every gateway would generate 100 lines of variables?

**Comment by fjtirado** [comment]
Yes, this unneded variables generation might be skipped (since this data is already in memory, it does not have performance impact though) 
Created JIRA https://issues.redhat.com/browse/KOGITO-6560
