### ISSUE TITLE
Kubernetes Discovery add-on but no official docs: Is this a prototype or will be ~supported?

### ISSUE THREAD

**Issue by StephenOTT** [kiegroup/kogito-runtimes#1922]
### Description

https://github.com/kiegroup/kogito-runtimes/tree/main/addons/common/kubernetes

**Comment by ricardozanini** [comment]
Hi! It's somewhat a prototype, you can see it in action here: https://github.com/kiegroup/kogito-examples/tree/main/kogito-quarkus-examples/onboarding-example

You have to [manually implement the WorkItemHandler](https://github.com/kiegroup/kogito-examples/blob/main/kogito-quarkus-examples/onboarding-example/onboarding-quarkus/src/main/java/org/kie/kogito/examples/BaseWorkItemHandlerConfig.java#L37) to name the services for the discovering logic to work. We want to remove this need and call it automatically based on the information in the BPMN/Serverless Workflow definitions.

**Comment by StephenOTT** [comment]
@ricardozanini is this https://github.com/kiegroup/kogito-examples/blob/main/kogito-quarkus-examples/onboarding-example/onboarding-quarkus/src/main/java/org/kie/kogito/examples/BaseWorkItemHandlerConfig.java#L72 the ~recommended way to create engine discoverability and other startup logic?  Is there a planned App/Engine Startup listener?

**Comment by ricardozanini** [comment]
HI, @StephenOTT. This is the "recommended" approach given a "tech trial" for now. No, there's no planning to add it to the startup listener for now. However, please reach out to me if you want to try it. I can figure out the best approach to move forward with this feature.
