### ISSUE TITLE
ZonedDateTime in pojo used in kogito process error in creating proto files

### ISSUE THREAD

**Issue by debu999** [kiegroup/kogito-runtimes#1985]
### Describe the bug

Hi team,
We are using kogito for a while now and are not able to use LocalDateTime, LocalDate, ZonedDateTime as default data types in classes used in bpmn2 version. Getting error like jandex cant find short . We use mongo db persistence. 
What data types are supported for proto file generation in the platform. Please advise.

### Expected behavior

We should have no errors for using datatypes like zonedatetime localdatetime etc. Now we only use String, Long and Date in our process variable classes. Please advise.

### Actual behavior

error. Jandex does not have class for all datetime fields.

### How to Reproduce?

take any example and use zonedatetime. The example should support platform independence.

**Comment by cristianonicolai** [comment]
@debu999 You can see the list of supported types based on the marshallers available here: https://github.com/kiegroup/kogito-runtimes/tree/main/jbpm/process-serialization-protobuf/src/main/java/org/kie/kogito/serialization/process/impl/marshallers
As for temporal ones, only Date is supported, but I created the following JIRA to track this request: https://issues.redhat.com/browse/KOGITO-6756

**Comment by cristianonicolai** [comment]
@debu999 the fix should land in version 1.18.0, feel free to reopen this if the problem persists.
