### ISSUE TITLE
Unable to build kogito-runtimes since, at least, the 7th of Feb's commit - can't find LogEvent

### ISSUE THREAD

**Issue by a-roberts** [kiegroup/kogito-runtimes#1995]
### Describe the bug

Hi there, first of all - a big thanks to everyone working on Kogito! I'm someone that's interested in building serverless workflows and this is awesome.

Onto the issue at hand, what I'd like to do is the build the latest version of kogito-runtimes, using a JDK 11.

What I see is

```
ERROR]   symbol:   variable LogEvent
[ERROR]   location: class org.jbpm.audit.KogitoWorkingMemoryLogger
[ERROR] /Users/adam/projects/kogito-runtimes/jbpm/jbpm-flow/src/main/java/org/jbpm/audit/KogitoWorkingMemoryFileLogger.java:[83,24] cannot find symbol
[ERROR]   symbol:   class LogEvent
[ERROR]   location: class org.jbpm.audit.KogitoWorkingMemoryFileLogger
[ERROR] /Users/adam/projects/kogito-runtimes/jbpm/jbpm-flow/src/main/java/org/jbpm/audit/KogitoWorkingMemoryInMemoryLogger.java:[50,24] cannot find symbol
[ERROR]   symbol:   class LogEvent
[ERROR]   location: class org.jbpm.audit.KogitoWorkingMemoryInMemoryLogger
[ERROR] -> [Help 1]
```

when I follow what's in the contributing guidelines.

So, clone what's in main and do

```
 ./mvnw clean install -Dquickly
```

to see the above, with:

```

bash-3.2$ java --version
openjdk 11.0.14 2022-01-18
OpenJDK Runtime Environment Temurin-11.0.14+9 (build 11.0.14+9)
OpenJDK 64-Bit Server VM Temurin-11.0.14+9 (build 11.0.14+9, mixed mode)
```

that's the latest JDK available from Adoptium. Not sure if any other variant is better, for my purposes I can just checkout an older commit (I picked the following

```
commit 6e9ab8aa8946ccf49135352474f103b5c4f374ef (HEAD)
Author: Tristan Radisson <tristan.radisson@gmail.com>
Date:   Tue Feb 1 14:59:04 2022 +0100

    KOGITO-6682 Force maven version to 3.8.1+ (#1962)
```

)

and I can build just fine again.

### Expected behavior

I'd love to build the latest kogito-runtimes code just grand

### Actual behavior

I get the stacktrace seen above with that JDK version

### How to Reproduce?

```
git clone https://github.com/kiegroup/kogito-runtimes.git
```

```
cd kogito-runtimes
```

(remain on the main branch)

```
./mvnw clean install -Dquickly
```

### Output of `uname -a` or `ver`

I'm on a Mac. Specifically here's the output from the above.

```
bash-3.2$ uname -a Darwin Adams-MBP 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64. 
```

### Output of `java -version`

```
openjdk 11.0.14 2022-01-18 OpenJDK Runtime Environment Temurin-11.0.14+9 (build 11.0.14+9)
OpenJDK 64-Bit Server VM Temurin-11.0.14+9 (build 11.0.14+9, mixed mode)
```

### GraalVM version (if different from Java)

Not in use

### Kogito version or git rev (or at least Quarkus version if you are using Kogito via Quarkus platform BOM)

main

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) Maven home: /Users/adam/.m2/wrapper/dists/apache-maven-3.8.4-bin/52ccbt68d252mdldqsfsn03jlf/apache-maven-3.8.4 Java version: 11.0.14, vendor: Eclipse Adoptium, runtime: /Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home Default locale: en_GB, platform encoding: UTF-8 OS name: "mac os x", version: "12.1", arch: "x86_64", family: "mac"
```

### Additional information

I'm getting my JDK from https://adoptopenjdk.net/archive.html?variant=openjdk11

Any help would be awesome. Perhaps we need to add something to contributing.md now? I noticed some big, awesome commits going on recently, for SW 0.8 spec, but I still expect things to build OK. 

I went back to an older commit before that change was introduced.

**Comment by radtriste** [comment]
Hi @a-roberts
The `kogito-runtimes` codebase is dependent on the [drools](https://github.com/kiegroup/drools) codebase.
Usually, there is build problem as we deploy snapshots every night. But since recently our Nexus instance is having some problems and it may be that it does not have the latest snapshot version available ...

A workaround is to clone https://github.com/kiegroup/drools and run `mvn clean install -Dquickly` in that repository before building kogito-runtimes.
