### ISSUE TITLE
Kogito SVG generation breaks with Quarkus 2.7.x - Breaks in windows

### ISSUE THREAD

**Issue by debu999** [kiegroup/kogito-runtimes#2116]
While upgrading to Quarkus Kogito SVG generation do not work when using any quarkus version >= 2.7.0.Final
it works perfectly fine with any version less than that viz. Works with 2.6.3 just fine. 
Need help tried with kogito version 1.19.0 as well not working with quarkus 2.7.x.
steps
Create a sample kogito app via code.quarkus.io.
update kogito to 1.19.0.Final
so you will have 2.7.5.Final Quarkus and 1.19.0.Final Kogito.

<dependency>
      <groupId>org.kie.kogito</groupId>
      <artifactId>kogito-addons-quarkus-process-svg</artifactId>
    </dependency>

svg endpoints do not work. Please have a look and fix it.

**Comment by debu999** [comment]
@evacchi Will there be anything to fix this. It seems to work with 2.6.3 but not with 2.7

**Comment by nmirasch** [comment]
Hello @debu999, I tried the SVG addon with 1.19.0.Final  Quarkus version 2.7.3.Final and it is working fine(i.e: https://github.com/kiegroup/kogito-examples/tree/stable/kogito-quarkus-examples/kogito-travel-agency/extended/travels) . Is there any log that can help to localize the reason why it's not working for you?

**Comment by debu999** [comment]
@nmirasch It seems its not working in windows and works fine in mac. Can you please help test the same. I get error 404 not found. Any logger to update to confirm what might be wrong.
<img width="824" alt="Screenshot 2022-04-01 at 7 19 28 AM" src="https://user-images.githubusercontent.com/1910577/161190846-5f3d493e-d242-44b8-8b16-98b6d57dd7dc.png">
<img width="821" alt="Screenshot 2022-04-01 at 7 20 16 AM" src="https://user-images.githubusercontent.com/1910577/161190848-62b4f9da-f131-4c53-abd6-de1f0e78e211.png">
[Archive.zip](https://github.com/kiegroup/kogito-runtimes/files/8394535/Archive.zip)
Attaching pom and applicaiton.properties.

**Comment by nmirasch** [comment]
@debu999 let me give this a try with windows then, to see if is there  any reason for this. Thanks!
(BTW, I see by the screenshot that you are trying with quarkus 2.8.0.CR1?)

**Comment by debu999** [comment]
> @debu999 let me give this a try with windows then, to see if is there  any reason for this. Thanks!
> (BTW, I see by the screenshot that you are trying with quarkus 2.8.0.CR1?)

It does bit matter. I tried with both code starter from code. quarkus.io and via plugin same issue

**Comment by debu999** [comment]
Just a simple application without dataindex.

**Comment by nmirasch** [comment]
@debu999 Finally, @fjtirado achieved to reproduce the issue in a Windows machine. It seems Quarkus has change the way it manages the FileSystemResources. This jira will track the fix: https://issues.redhat.com/browse/KOGITO-6931
Thanks both!

**Comment by debu999** [comment]
@fjtirado @nmirasch thanks can you please guide how did you debug. It will save more time in future while reporting we will investigate at our end as well. With log level set to all as well could not get any error

**Comment by nmirasch** [comment]
@debu999 usually what I do is to start the app in dev mode with the command 
'mvn clean compile quarkus:dev'
and it starts automatically (by default) the debug port 5005, you can find here the details https://quarkus.io/guides/maven-tooling#debugging

**Comment by debu999** [comment]
Seems it's fixed in 1.20.0.Final

**Comment by debu999** [comment]
Closing ticket now
