### ISSUE TITLE
Kogito's getById API returning null values for Enum fields (even though data is present in database)

### ISSUE THREAD

**Issue by prerana15** [kiegroup/kogito-runtimes#2365]
### Describe the bug

Kogito's getById API returning null values for Enum fields (even though data is present in database).
This happens only when enum is part of nested class in the Main Process model.

### Expected behavior

get and getById API should return values as saved :

{
"id":"string",
"a":{
"abc": "abc",
"classBvar":{
"somevar":"var",
"enumVar":"TEST1"
}
}
}

### Actual behavior

{
"id":"string",
"a":{
"abc": "abc",
"classBvar":{
"somevar":"var",
"enumVar":null
}
}
}

### How to Reproduce?

**Scenario**: 1) Add process variable of type class A in bpmn for any test process. and generate kogito code.
2) run post API for test process with following payload:
{
"a":{
"abc": "abc",
"classBvar":{
"somevar":"var",
"enumVar":"TEST1"
}
}
}

**Sample code:**
public Class A{
private String abc;
private B classBvar;
}

public class B{
private String somevar;
private TestEnum enumvar;
}

public enum TestEnum{
TEST1,
TEST2
}

**Comment by cristianonicolai** [comment]
@prerana15, which database are you using?

**Comment by prerana15** [comment]
Mongo db

**Comment by prerana15** [comment]
@cristianonicolai,  Could you please update on this issue?

**Comment by cristianonicolai** [comment]
Created https://issues.redhat.com/browse/KOGITO-7712 for tracking

**Comment by cristianonicolai** [comment]
Fixed by https://github.com/kiegroup/kogito-runtimes/pull/2381, should be included in 1.26.0 release
