### ISSUE TITLE
Support for Java's List data type for process variable in kogito bpmn

### ISSUE THREAD

**Issue by prerana15** [kiegroup/kogito-runtimes#2366]
### Description

As per my understanding, Kogito does not support the java's List data type while creating process variable in bpmn.
Is their a plan of adding the support in future releases? Or is it already supported in any newer versions?

**Comment by cristianonicolai** [comment]
@prerana15 java List is currently supported in Kogito. Are you facing any particular issues with it?

**Comment by prerana15** [comment]
@cristianonicolai , let me check again. I think we were facing issues during compile time.
Will update you soon.

**Comment by prerana15** [comment]
@cristianonicolai , these are the steps I followed for adding List type variable in Bpmn process. 
1) import Java.until.List in bpmn
2) under process variable, add a variable of List<Object> type. 
3) Save and compile.

Expected Result:
Code compiles successfully and proto is generated.

Actual:
Build failed with error - “can not find symbol” class List.

please let me know what am I missing or doing wrong here.

**Comment by cristianonicolai** [comment]
@prerana15 if you're using persistence, you need to use a typed List in order to generate the correct proto. See an example here: https://github.com/kiegroup/kogito-runtimes/blob/main/quarkus/integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-processes-persistence-common/src/main/resources/MultipleInstanceSubProcess.bpmn#L3 Note that the editor does escapes `<` and `>` automatically.

**Comment by prerana15** [comment]
@cristianonicolai . Thank you for responding. I will check the example given by you and let you know for any issues.

**Comment by cristianonicolai** [comment]
Feel free to reopen if you find any issues.

**Comment by prerana15** [comment]
Hi @cristianonicolai ,
I tried the example you had given. But instead of List<String> I had to use List<Example> as per my requirement.
(Example --> POJO)
Now i do not see any build errors, Protos generated perfectly and application starts well.
I was able to POST the request but when i tried getByID API, Its throwing following exception during serialization:
CausedBy: ProcessInstanceMarshallerException
CausedBy: java.lang.ClassNotFoundException: com.example.Example

Could you please check on this one?
