### ISSUE TITLE
Patch call in kogito runtime to update the domain object data

### ISSUE THREAD

**Issue by debu999** [kiegroup/kogito-runtimes#2394]
### Description

Kogito have Patch for Task Instance. 
But no patch for Process Instance and Domain APIs.
When executing the same, it does not update the acutal domain object information. Need a option to confirm how acutal domain object needs to be udpated in Kogito. 

We were using domain object put call for data updates. So if a workflow is **test.bpmn**
Then we have test resources created which in eternity does provide a get call and a put call. But no patch call. Can we have a patch call for domain APIS. this will allow to save data in our system as requrired
![Screenshot 2022-08-12 at 10 25 41 AM](https://user-images.githubusercontent.com/1910577/184287691-3f3b0246-d103-488f-9296-afd0b41d7091.png)

### Implementation ideas

provide a patch call in domain models apis so only the keys in the payload gets updated in the domain.

Do share to update the domain object what needs to be done otherwise.
we do run get call and then udpate the payload then put call to update again. This is time consuming and should be provided as a patch method only for keys in payload to get updated.

**Comment by fjtirado** [comment]
Fixed with https://issues.redhat.com/browse/KOGITO-7713

**Comment by debu999** [comment]
As discussed, for tasks patch will be added as well this only updates patch for process.
