### ISSUE TITLE
Error handling with event subprocess does not execute "catch" and "finally" blocks of a parent process's task handler

### ISSUE THREAD

**Issue by tokarenko** [kiegroup/kogito-runtimes#2409]
### Describe the bug

I suppose that error handling with event subprocess as described in [Error handling in Kogito](https://blog.kie.org/2021/07/error-handling-in-kogito.html) doesn't work as expected. When task handler code throws an exception, code execution flow breaks immediately and passes to subprocess for error handling. Thus, "catch" and "finally" blocks do not get executed. I suppose that they must be executed before passing to error handling subprocess.

For example, I tried to capture trace log for any technical error within a process. This works as expected with boundary error event. When I switch to event subprocess code execution stop at "throw new IllegalArgumentException("Exception")" and never reach "catch" and "finally" blocks.

```
@ApplicationScoped
public class TaskHandler {
  public void Execute() throws Exception {
    try {
          throw new IllegalArgumentException("Exception");
        }
    } catch (Exception e) {
      Log.trace(ExceptionUtils.getStackTrace(e));
      throw e;
    } finally {
      Log.info("Reached finally block");
    } 
  }
}
```

### Expected behavior

"catch" and "finally" blocks must be executed before passing to error handling subprocess

### Actual behavior

"catch" and "finally" blocks do not execute before passing to error handling subprocess

**Comment by fjtirado** [comment]
@tokarenko Can you provide a reproducer with a bpmn?

**Comment by tokarenko** [comment]
I can't reproduce anymore. Works as expected.
