### ISSUE TITLE
kogito artifacts missing license

### ISSUE THREAD

**Issue by debu999** [kiegroup/kogito-runtimes#2564]
### Describe the bug

kogito-addons-monitoring-api / protobuf-serialization-protobuf / kogito-serverless-workflow-spring-boot-starter  no license in the artifacts.

### Expected behavior

kogito-addons-monitoring-api / protobuf-serialization-protobuf / kogito-serverless-workflow-spring-boot-starter  add in parent license in the artifacts.

### Actual behavior

need license in the artifacts to use.

### How to Reproduce?

Could not use the artifacts without license in our org.

### Kogito version or git rev (or at least Quarkus version if you are using Kogito via Quarkus platform BOM)

1.29.0.Final

### Additional information

need update to add in required licenses in artifacts.

**Comment by nmirasch** [comment]
There are referenced artifacts that were removed from the repo, the bom needs to be updated to remove them properly.
This jira to track the fix https://issues.redhat.com/browse/KOGITO-8154

**Comment by nmirasch** [comment]
Fix have been merged, it will be available at 1.30.0.Final. Thanks for bring this up!
