### ISSUE TITLE
Custom type x is no supported by Kogito persistence

### ISSUE THREAD

**Issue by Mert18** [kiegroup/kogito-runtimes#2593]
### Describe the bug

I am using Kogito (1.26.0) with quarkus (2.9.2) and deploying containers infinispan(13.0.2), data-index(1.29), , jobs-service(1.29)... as described in kogito-examples, process-usertasks-timer-quarkus-with-console: https://github.com/kiegroup/kogito-examples/tree/stable/kogito-quarkus-examples/process-usertasks-timer-quarkus-with-console

I am also using a library that uses Okhttp which is not Serializable and I get the following error while building my application.
![Screenshot from 2022-11-03 11-12-15](https://user-images.githubusercontent.com/40024436/199673274-faacca9d-978b-45e0-83ad-235fa689f4f4.png)

When I tag this variable as "internal", this error disappears but breaks other things in my application. Is there a way to prevent this error other than making this class Serializable? Because it is an external class and not easy to modify. Thanks in advance.

### How to Reproduce?

1. Use a library that uses okhttp inside.
```  
<dependency>
  <groupId>io.kubernetes</groupId>
  <artifactId>client-java</artifactId>
  <version>15.0.1</version>
</dependency>
```
Deploy necessary containers for persistence: https://github.com/kiegroup/kogito-examples/tree/stable/kogito-quarkus-examples/process-usertasks-timer-quarkus-with-console (in docker-compose/...infinispan.yaml)
Add necessary dependencies
```
    <dependency>
      <groupId>org.kie.kogito</groupId>
      <artifactId>kogito-addons-quarkus-persistence-infinispan</artifactId>
    </dependency>
    <dependency>
      <groupId>org.kie.kogito</groupId>
      <artifactId>kogito-addons-quarkus-events-process</artifactId>
    </dependency>
    <dependency>
      <groupId>org.kie.kogito</groupId>
      <artifactId>kogito-addons-quarkus-jobs-management</artifactId>
    </dependency>
    <dependency>
      <groupId>org.kie.kogito</groupId>
      <artifactId>kogito-addons-quarkus-process-management</artifactId>
    </dependency>

    <dependency>
      <groupId>org.kie.kogito</groupId>
      <artifactId>kogito-addons-quarkus-process-svg</artifactId>
    </dependency>

```
2. Create a .bpmn2 file and create a process variable that has a type of "io.kubernetes.client.openapi.ApiClient"
3. Try to build the application
`mvn clean install`

### Output of `java -version`

11

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 4.0.0

**Comment by fjtirado** [comment]
@Mert18 
Why do you need to have the ApiClient object as bpmn property?

**Comment by Mert18** [comment]
I have such a long process and I'm using ApiClient throughout the process in different nodes, I didn't want to create client for each node seperately, instead I wanted to create once in the process and give it as input in other nodes.

But I guess I'll just remove ApiClient from the process and create it in the functions. Thank you.
