### ISSUE TITLE
Kogito Data Index Service as container

### ISSUE THREAD

**Issue by wtrocki** [kiegroup/kogito-runtimes#271]
Downloading jar manually and executing it can be hard task. 
It will be much easier to build data index container on github releases.
The container could be used only for demo/examples and it can use empirical volume

**Comment by wtrocki** [comment]
After quick check I have realized that container might be overkill. It will be cool to get maven target at least that will use some preconfigured path for storing index files.

All of this is in relation to the example app: https://github.com/mswiderski/kogito-travel-agency-tutorial

**Comment by ricardozanini** [comment]
Hi!

We already have an image (https://github.com/kiegroup/kogito-cloud/blob/master/s2i/kogito-data-index-overrides.yaml) for the Data Index service and support for it in the operator:

https://github.com/kiegroup/kogito-cloud-operator

Helps?

**Comment by ricardozanini** [comment]
Why not closing it? :smiley:

**Comment by wtrocki** [comment]
Sorry. My intention was to close it.
