### ISSUE TITLE
need restapi to get user task belong to specific user or group

### ISSUE THREAD

**Issue by kstan79** [kiegroup/kogito-runtimes#2712]
### Description

Is there anyway to filter user task belong to specific actor or group using openapi? Or, I can get group, actor of the task. 

I notice that the only way to filter that using graphql/dataindex. I wish to avoid that due to:
1. it added complexity of infrastructure
2. i wish my team using generated openapi client instead of code manually

### Implementation ideas

I propose:
create api filtered by actor or group
`get /{bpmn-flow}/task-byactor/{actorname}`
`get /{bpmn-flow}/task-bygroup/{groupname}`
result will be array of usertask: `[{usertaskid:xx1 ,  data: {...}}, {usertaskid:xx2, data:{...}}]`

**Comment by debu999** [comment]
is this not a simple api to get from UserTaskInstance Collection if using MongoDB or any other persistence?

potentialGroups/adminGroups/potentialUsers/ActualOwner etc.

![Screenshot 2022-12-29 at 2 37 36 PM](https://user-images.githubusercontent.com/1910577/209929136-a2772287-0941-4a03-b828-93cde7c58780.png)

**Comment by kstan79** [comment]
Oh cause official and stable way definitely go through rest api. My plan is We use openapi-generator to generate the typescript client code.

**Comment by fjtirado** [comment]
As indicated by @debu999 , Kogito is not going to define specific rest api for any filter combination. The whole idea behind data index is againts that approach.
