### ISSUE TITLE
Support for Quarkus 3.x

### ISSUE THREAD

**Issue by debu999** [kiegroup/kogito-runtimes#2716]
### Description

I believe one of the biggest change to Quarkus 3.x is Javax to Jakarta migration.
Is there any plan on providing similar changes on kogito ?

### Implementation ideas

Quarkus have launched 3.0.0.Alpha2 version now. Is there any tips on how to test kogito with Quarkus 3.x??

**Comment by hbelmiro** [comment]
Hi @debu999.
Kogito still doesn't support Quarkus 3. There are plans to support it soon, but we cannot estimate yet.
