### ISSUE TITLE
PMML support

### ISSUE THREAD

**Issue by rimolive** [kiegroup/kogito-runtimes#277]
I'm working on getting a PMML model exposed as a microservice and found that kogito will be the best fit on that.

It would be great if kogito has PMML support. If there are already plans for it, please provide an ETA.

**Comment by gitgabrio** [comment]
HI @rimolive 
I'm the responsible of the Trusty PMML development.

We are actively working on Kogito-PMML integration and currently there are two options
1) directly invoking a PMML through generated "prediction" REST endpoint.
2) use DMN "as gateway" to invoke the PMML

With solution 1) the new Trusty PMML implementation will be invoked, but the current coverage of the specification is limited.
With solution 2) it is possible to use the jpmml implementation (that of course is complete) but you have to write the DMN that invokes the PMML.

Last, native compilation of PMML (but only with Trusty implementation) will be available probably with kogito 0.16

Feel free to contact me for better explanations, questions, etc.

Best

Gabriele
