### ISSUE TITLE
The link to the Quarkus guide is dead

### ISSUE THREAD

**Issue by YassinHajaj** [kiegroup/kogito-runtimes#2973]
### Describe the bug

Various links are dead regarding the Quarkus Kogito guide.

The one present in the README.md is not working neither.

Here is a list of what works and what not

- ❌ https://quarkus.io/guides/kogito
- ❌ https://quarkus.io/version/main/guides/kogito
- ✅ https://quarkus.io/version/2.13/guides/kogito
- ✅ https://quarkus.io/version/2.7/guides/kogito

**Comment by radtriste** [comment]
@YassinHajaj We did not make Quarkus 3 yet, nor platform
So for now, Kogito has been removed from Quarkus main :)

**Comment by YassinHajaj** [comment]
Oh, ok.. Is it coming though ?
Maybe only the readme.md can be fixed then to point to 2.13 ?

**Comment by radtriste** [comment]
Oh yes will correct that !

**Comment by radtriste** [comment]
The compatibility with Quarkus 3 is coming and should be available in the next weeks.

About having Kogito into Quarkus platform 3, there is no plan yet as there are quite some changes in the project and we don't want to block any part of it. More to come I guess but for now, I cannot give any ETA.

**Comment by radtriste** [comment]
doc updated
