### ISSUE TITLE
ForEach with RestWorkItemHandler Joined result array is overlapped

### ISSUE THREAD

**Issue by flex-myeonghyeon** [kiegroup/kogito-runtimes#2992]
### Describe the bug

v1.36.1.Final is stable
v1.37.0.Final occurred this bug.
related PR: https://github.com/kiegroup/kogito-runtimes/pull/2909 @fjtirado 

---

This [Solving Math Problems Example](https://github.com/serverlessworkflow/specification/tree/main/examples#solving-math-problems-example) outputCollection result is expected `{"results" : [4, 3, 30, 10] }` 
```json
"states":[
{
 "name":"Solve",
 "type":"foreach",
 "inputCollection": "${ .expressions }",
 "iterationParam": "singleexpression",
 "outputCollection": "${ .results }",
 "actions":[
   {
      "functionRef": {
         "refName": "solveMathExpressionFunction",
         "arguments": {
           "expression": "${ .singleexpression }"
         }
      }
   }
 ],
...
```

But outputCollection is `[[{"result":4}],[{"result":3}],[{"result":30}],[{"result":10}]]`. (array is overlapped)
<img width="829" alt="스크린샷 2023-05-18 오전 9 32 17" src="https://github.com/kiegroup/kogito-runtimes/assets/117622409/0e645a1f-51f9-4b34-a152-8e25608e4608">

---

RestWorkItemHandler targetInfo evaluated `Object.class` then result convert to `io.vertx.core.json.JsonObject`.
`JsonObjectUtils#fromValue` evaluated JsonObject to Iterable even result is object. (io.vertx.core.json.JsonObject implements Iterable)
<img width="672" alt="스크린샷 2023-05-18 오전 10 01 31" src="https://github.com/kiegroup/kogito-runtimes/assets/117622409/cc16f2ba-27a4-4261-bcd1-acc5e9e408e9">

I suggest change to RestWorkItemHandler evaluated targetInfo type be `JsonNode.class` type to correct result for ForEach state.

### Expected behavior

This [Solving Math Problems Example](https://github.com/serverlessworkflow/specification/tree/main/examples#solving-math-problems-example) outputCollection result is expected `{"results" : [4, 3, 30, 10] }` 

### Actual behavior

`[[{"result":4}],[{"result":3}],[{"result":30}],[{"result":10}]]`. (array is overlapped)

### How to Reproduce?

Run this example [Solving Math Problems Example](https://github.com/serverlessworkflow/specification/tree/main/examples#solving-math-problems-example)

And debbugging check `JsonObjectUtils#fromValue` evaluated `io.vertx.core.json.JsonObject`

### Output of `java -version`

11

### Kogito version or git rev (or at least Quarkus version if you are using Kogito via Quarkus platform BOM)

1.37.0.Final

**Comment by fjtirado** [comment]
@flex-myeonghyeon 
Thanks for the detailed explanation. 
The problem here is that JsonNode is an iterable, therefore the check should be instanceof collection. I have opened https://issues.redhat.com/browse/KOGITO-9167
But, even when this is fixed, if your rest is returning` {"result":4`}, the output will be 
`"results":[{"result":4},{"result":3},{"result":30},{"result":10}]`
To achieve as output
`"results":[4,3,30,10]`
you need to add 
"actions":[
   {
      "functionRef": {
         "refName": "solveMathExpressionFunction",
         "arguments": {
           "expression": "${ .singleexpression }"
           }
        },
      "actionDataFilter": {
                "results": "${.result}"
        }      
    }
]

**Comment by flex-myeonghyeon** [comment]
@fjtirado Thanks for your feedback

JsonNode is an iterable but evaluate JsonNode itself.
https://github.com/kiegroup/kogito-runtimes/blob/db1aace7cd274d679aff27d2d36aeb1c7ab9f90c/kogito-workitems/kogito-jackson-utils/src/main/java/org/kie/kogito/jackson/utils/JsonObjectUtils.java#L52

**Comment by fjtirado** [comment]
@flex-myeonghyeon 
Im using a different approach to fix the issue.

**Comment by fjtirado** [comment]
PR opened

See this actionDataFilter usage: https://github.com/kiegroup/kogito-runtimes/pull/2994/files#diff-dd2aca1b305f5d4b5862534162d6615f54fcf82e4e5541ecd8ec37428724087fR30
