### ISSUE TITLE
kogito-quarkus: modify() multiple properties

### ISSUE THREAD

**Issue by antoniomacri** [kiegroup/kogito-runtimes#746]
Hope this is the correct project to address this issue.

I'm using the Quarkus extension.

If I have:
```
modify($evaluation) {
    setPropA(true);
    setPropB(10);
}
```
it is compiled into:
```
{
   ($evaluation).setPropB(10);
   drools.update($evaluation,
                 mask_$evaluation);
}
```

If I use two modify()s, it turns into:
```
{
   ($evaluation).setPropA(true);
   drools.update($evaluation,
                 mask_$evaluation);
}
{
   ($evaluation).setPropB(10);
   drools.update($evaluation,
                 mask_$evaluation);
}
```

However in both cases the bitmask is defined on a single property:
```
final BitMask mask_$evaluation = BitMask.getPatternMask(DomainClassesMetadata76FC63AECA4701...Metadata_INSTANCE,
                                                                                          "propA");
```

Is there any chance to support modifying muliple properties at once?

**Comment by mariofusco** [comment]
According to drools drl syntax you're writing that modify block mistakenly. The setters should be separated by a comma like in

```
modify($evaluation) {
    setPropA(true),
    setPropB(10)
}
```

I agree that the fact that kogito is taking care of only one of the 2 statements instead of emitting a compile time error is misleading. I will fix this.
