### ISSUE TITLE
DMN integration with OpenAPI support potential?

### ISSUE THREAD

**Issue by dhartford** [kiegroup/kogito-runtimes#95]
Hi Team,
Been swapping between RHPAM 7.3 and a Quarkus/Kogito based immutable infrastructure decision-server approach, and going to at least ask the question:

Seeing things like the kogito-dmn-rest-utils library, are there any potential ideas/approaches to make stronger openAPI contracts that define the actual InputModels rather than a generic dmn-context approach?

i.e. some way to interrogate DMNItemDefinitionInfo to through codegen or some other mechanism create an equiv complex pojo/json struct that strongly types the openAPI interface for a given DMN model?

(I may have worded this slightly incorrect, but hoping the intent is transferred!)

**Comment by dhartford** [comment]
Forgot to add - this ability to create a struct would also be useful for other transport/protocol approaches as well (for example, AMQP), so although the initial/primary usecase is for REST/OpenAPI, it can be used elsewhere to help create better contracts of how to send data to DMN based decision services.

**Comment by mswiderski** [comment]
I'd say yes, this is what we are aiming for and already used in one of the examples, see here https://github.com/kiegroup/kogito-examples/blob/master/onboarding-example/payroll/src/main/java/org/kie/kogito/examples/VacationDaysDMNEndpoint.java#L41
that exactly opens it up for complete and type safe REST api that combined with openapi/swagger gives consumers way easier start

@tarilabs just so you're aware of....

**Comment by tarilabs** [comment]
Thanks @mswiderski for the ping and indeed that's what we are aiming for @dhartford 

In fact thank you for the question @dhartford , as you might have noticed, the REST endpoints are per-model or per-service, and with Kogito the intention is to avoid the "generic payload" which is instead the approach used on Kie Server.

Just a word of warning, tho, about "strong typing": DMN and especially FEEL is more of a dynamic type, so while we are aiming to generate OpenAPI/Swagger documentation/contracts/etc, we still want to support the intrinsic nature of DMN/FEEL.

In the end I expect for each REST endpoint you will have a clear description contract and documentation, so for instance if the DMN model has 2 Input Data, in that contract will be listed explicitly the requirements and output of the REST endpoint as based on the model.

On Kie Server, this is available via GET method which returns the description of the model, but I concur is not an OpenAPI descriptor.

Available if any further questions or doubts

**Comment by dhartford** [comment]
Thanks @tarilabs and @mswiderski for the quick responses!
I'm reviewing https://github.com/kiegroup/kogito-examples/blob/master/onboarding-example/payroll/src/main/java/org/kie/kogito/examples/VacationDaysDMNEndpoint.java#L41 , and more specifically the _generated_ models used, to see how far the team has already gotten  - this is actually pretty exciting!

**Comment by dhartford** [comment]
Question: what is the 'data modeler tool' used to generate the pojo and how to recreate the process?

/**
 * This class was automatically generated by the data modeler tool.
 */

**Comment by mswiderski** [comment]
That is the workbench data model editor

**Comment by dhartford** [comment]
Ah, the DMN InputData re-creates a Structure that has parity (maps to) the model, in that they are disconnected but coupled-by-convention only (manually).

**Comment by tarilabs** [comment]
@dhartford I'm not really sure I fully understand your last statement, but please notice DMN being still under active development, I expect this will be eventually be further simplified by automated code generation.

**Comment by dhartford** [comment]
I'll restate - it appears of you are doing DMN-first development, and you create the InputData, in order to make a stronger OpenAPI definition / message model, you then have to manually create a POJO a specific way to follow the convention of the name(s) used in the InputData and keep the two in-sync manually.

Obviously, if you are developing Domain/Pojo first and then creating InputData by following the convention of the existing Pojo, not as bad but still room for errors, but when you are doing DMN input first seems a bit clunky.

Absolutely recognize DMN (and kogito itself) under active development :-)

**Comment by ravim786** [comment]
the example link of onboarding is broken.

**Comment by tarilabs** [comment]
Hi @ravim786 which link is broken, please?

Can you provide a permalink or a screenshot?

Thanks,
MM

**Comment by ravim786** [comment]
The reference link above 
[https://github.com/kiegroup/kogito-examples/blob/master/onboarding-example/payroll/src/main/java/org/kie/kogito/examples/VacationDaysDMNEndpoint.java#L41](https://github.com/kiegroup/kogito-examples/blob/master/onboarding-example/payroll/src/main/java/org/kie/kogito/examples/VacationDaysDMNEndpoint.java#L41)

**Comment by tarilabs** [comment]
Yes it's normal that is an old link; now DMN REST endpoints are
code-generated automatically by Kogito, based on the DMN assets.

So kogito will scan the assets, which for that example are present here:
https://github.com/kiegroup/kogito-examples/tree/master/onboarding-example/payroll/src/main/resources/org/kie/kogito/examples/payroll
and will generate automatically the REST endpoint, as usual.

Hope that clarifies,
MM

**Comment by tarilabs** [comment]
Considering this issue as resolved since https://issues.redhat.com/browse/BAPL-1616 enables "strongly typed" feature on Kogito and consequently Swagger/OpenAPI is generated as part of the Kogito build
